# Generated by Django 2.2.6 on 2019-10-31 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonStory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChechenDjango.Person')),
                ('personType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChechenDjango.PersonType')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChechenDjango.Story')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorStory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChechenDjango.Author')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChechenDjango.Story')),
            ],
        ),
    ]
