# Generated by Django 2.2.6 on 2019-11-01 03:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ChechenDjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personstory',
            name='subName',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
